# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Plugin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IonicRunner
  pod 'Capacitor'

  pod 'FBSDKCoreKit', '~> 4.44.1'
  pod 'FBSDKLoginKit', '~> 4.44.1'
end

target 'PluginTests' do
  use_frameworks!

  pod 'Capacitor'
  pod 'FBSDKCoreKit', '~> 4.44.1'
  pod 'FBSDKLoginKit', '~> 4.44.1'
end
